//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tbl_invoice_products = new HashSet<tbl_invoice_products>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<int> stock_quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice_products> tbl_invoice_products { get; set; }
    }
}
