//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice_payments
    {
        public int payment_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string payment_date { get; set; }
        public Nullable<double> payment_ammount { get; set; }
        public string payment_mode { get; set; }
        public string payment_description { get; set; }
    
        public virtual tbl_invoice_details tbl_invoice_details { get; set; }
    }
}
